name: trade

services:
  postgres:
    container_name: trade-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: order_execution
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - trade_postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: trade-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - trade_redis_data:/data

volumes:
  trade_postgres_data:
  trade_redis_data:
